INSERT INTO RZL_Q1 (question,answer)VALUES('Maestro _____ _____ became the hero’s tutor in Spanish and Latin. He was a classmate of Don Francisco','Leon Monroy'),
('Rizal Youngest Sister','Soledad'),
('Rizal Sister whom he learned the value of sisterly love','Conception'),
('Rizal Sister who inherited his properties in Dapitan','Trinidad'),
('Rizal Epileptic Sister','Josefa'),
('Rizal Eldest Sister','Saturnina'),
('It is the poem wher Rizal expressed the importance of loving ones native language','To My Fellow Children'),
('Rizal teacher in Binan','Maestro Justiniano'),
('Rizal private teacher who honed his skillfulness in latin','Leon Monroy'),
('It is a form of heavy taxation','Tribute'),
('Rizal Complete Birthday','June 19, 1861'),
('Rizal First private tutor','Maestro Celestino'),
('Rizal godfather when he was baptised as catholic','Fr. Perdo Casanas'),
('He pioneered the secularization of parishes','Fr. Pedro Pelaez'),
('The preist who baptised Rizal','Fr. Rufino Collantes'),
('True or False<br>Rizal Uses Charcoal in his writing session','True'),
('True or False<br>Rizal Uses Chalk in his writing session','False'),
('Dona Teodora alleged conspired for poisoning her sister-in law','True'),
('What is age of Rizal when he experienced the first Rizal','4'),
('He taught Rizal in drawing','Jose Alberto'),
('He taugh Rizal in the Rudiments of wrestling','Manuel'),
('Rizal painting partner under the instruction of Mang Juancho','Jose Guevarra'),
('He almost broke Rizal arm during arm wrestling','Andres Salandan'),
('True or False<br>Gregorio was influenced Rizal in fencing','True'),
('True or False<br>Mercado means Market','True'),
('It is a forced Labor rendered by all males to the government','Polo'),
('True or False<br>Moth & Flame story reminded jose to pray his mother','True'),
('Jose Rizal second private tutor','Maestro Lucas Padua'),
('He gave wise direction in the studies of Jose','Uncle Jose Alberto'),
('He instilled into the mind of Jose the love for education','Uncle Gregorio'),
('the mode of transportation','Carromata'),
('Formal teacher of Rizal','Maestro Justiniano Aquino Cruz'),
('He freely gave Jose painting lessons','Old Juancho'),
('Jose Rizal and his classmate ____ ________ became apprentices of Old Juancho','Jose Guevarra'),
('True or False<br>Jose surpassed his classmates in Spanish, Latin and other subjects','True'),
('When Jose left Biñan','December 17, 1870'),
('the steamer that Jose rode','Talim'),
('Arturo Camps is a Frenchman and a friend of Don Francisco, he took care of Jose during the trip','True'),
('When did Cavite Mutiny happened?','January 20, 1872'),
('When did GOMBURZA executed?','February 17,1872'),
('True or False<br>The martyrdom of the three priests inspired Rizal to fight the evils of Spanish tyranny','True'),
('In 1891, Rizal dedicated his second novel __ ________to GOMBURZA','El Filibusterismo'),
('Fullname of Dr. Jose Rizal','JOSE PROTACIO RIZAL MERCADO Y ALONZO REALONDA'),
('True or False<br>which served as the first governmental system in the Philippines, land control was delegated to selected Spanish officials or religious orders','True'),
('a form of heavy taxation paid annually by each family or single individual, symbol of vassalage to Spain','Tribute'),
('Polo – compulsory service to the government rendered annually by all males age from ________ years old','16-60'),
('________ - prohibited the people from trading with other Asian countries in order to ward off the expressed interests of other colonial powers over the islands','Isolation policy'),
('__________ - rule of the friars, which made the clergy to obtain, by way of Royal Patronage, certain political powers and privileges which were gravely abused leading to the misery of many','Frailocracy'),
('This revolution include modern ideas such as human rights, liberalism, justice and equality have become popular over Europe and America','Intellectual Revolution'),
('This revolution includes had pushed the countries to become progressive leading to the fall of traditional monarchies','Industrial Revolution'),
('True or False<br>Independence of Mexico led to the death of Galleon Trade which forced the Madrid government to open the Philippines to world trade','True'),
('Rizal’s great, great grandfather was a Chinese Immigrant','Domingo Lamco'),
('Domingo Lamco married a Filipina named _______ __________ _______','Ines Dela Rosa'),
('Rizal, from latin “______” means “green fields”','ricial'),
('True or False <br>Francisco Mercado was a businessman from Binan, Laguna','True'),
('Who is the father or Rizal?','Francisco Mercado'),
('She is the mother of Rizal','Dona Teodora'),
('She married Manuel Hidalgo of Tanauan, Batangas. In 1909 Doña Saturnina published Pascual Poblete’s Tagalog translation of the Noli Me Tangere','Saturnina'),
('She married Antonino Lopez, a teacher and musician from Morong, Rizal. It is said that She could recite from memory almost all the poems of Rizal.','Narcisa'),
('She married Silvestre Ubaldo, a telegraph operator from Manila','Olimpia'),
('She married Mariano Herbosa of Calamba, Laguna.','Lucia'),
('She married Daniel Faustino Cruz of Biñan, Laguna','Maria'),
('Jose Rizal _th of the 11 children & second son of Francisco Mercado and Teodora Alonzo.','7'),
('She who followed Jose, died when Rizal was four.','Conception'),
('She was the custodian of Rizal’s elegy, “Mi Ultimo Adios.”','Trinidad'),
('She married Pantaleon Quintero of Calamba, Laguna. Soledad, who became a teacher, is said to have been “the best educated” among Rizal’s sisters','Soledad'),
('True or False<br>The family of rizal belonged to the Principalia class','True'),
('True or False<br>Rizal Would never forget the story, “The Moth and the Flame” from the book El Amigo de los Niños','True'),
('an artist, who taught him skills in sketching and drawing the used of pencil and charcoal','Jose Alberto'),
('an athlete instruct him the rudiments of fencing and wrestling','Manuel'),
('At the age of _ Rizal wrote an untitled poem about love, he expressed the Tagalog language as one that is equal footing with Latin & Spanish','8'),
('True or False<br>By 9 yrs. Old (1870) – sent to Biñan to study under the instruction of Maestro Justiniano Aquino Cruz','True'),
('He is the first one Rizal had brawl with','Pedro'),
('True or False<br>1871 – Rizal’s Biñan studies ended','True'),
('True or False<br>18 February 1872 – the GOMBURZA were executed','False'),
('True or False<br>GOMBURZA Execution was upon the order of Gov. Gen. Rafael Izquierdo','True')